{% set name = "disnake" %}
{% set version = "2.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/disnake-{{ version }}.tar.gz
  sha256: b6b33ba95c9d220f64fb17413d0c0ffd89708dc30510e9900a1d9990b69b929f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.7.0,<4.0

test:
  imports:
    - disnake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DisnakeDev/disnake
  summary: A Python wrapper for the Discord API
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - disnake/bin/COPYING

extra:
  recipe-maintainers:
    - MisileLab
