{% set name = "disnake" %}
{% set version = "2.10.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/disnake-{{ version }}.tar.gz
  sha256: e469938c72f88432b55bc5f521a260f027d3db9e5337fe0f28098f3bfafc5a43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{python_min}}
    - aiohttp >=3.7.0,<4.0

test:
  imports:
    - disnake
  commands:
    - pip check
  requires:
    - python {{python_min}}
    - pip

about:
  home: https://github.com/DisnakeDev/disnake
  summary: A Python wrapper for the Discord API
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - disnake/bin/COPYING

extra:
  recipe-maintainers:
    - MisileLab
