{% set name = "disnake" %}
{% set version = "2.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/disnake-{{ version }}.tar.gz
  sha256: 0e062042b103b18601b62cc25b301ef837b40af2de15efeb7108466078243bb8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.7.0,<4.0
    - audioop-lts; python_version >= "3.13"

test:
  imports:
    - disnake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DisnakeDev/disnake
  summary: A Python wrapper for the Discord API
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - disnake/bin/COPYING

extra:
  recipe-maintainers:
    - MisileLab
