{% set name = "disnake" %}
{% set version = "2.12.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/disnake-{{ version }}.tar.gz
  sha256: 5e1e71dbbb18595ed8767262bc908aa66eab5e2cb86bfca7f3b20754e6a5433f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.27.0
    - versioningit >=3.3.0,<4
    - packaging
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.7.0,<4.0
    - typing_extensions >=4.1
    - yarl >=1.0

test:
  imports:
    - disnake
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/DisnakeDev/disnake
  summary: A Python wrapper for the Discord API
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - disnake/bin/COPYING

extra:
  recipe-maintainers:
    - MisileLab
